language: node_js
node_js:
  - 0.7
before_script:
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"
  - npm install connect
  - sudo node test/ci/server.js &
  - sleep 5
script: phantomjs test/ci/run-qunit.js 'http://localhost:80/test/index.html'