notifications:
  email:
    - cameron.d.prebble@gmail.com
language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli bower
  - bower install
branches:
  except:
    - docs
    - gh-pages
